name: PHPUnit

on:
  # Commits made in Duster Fix will not trigger any workflows
  # This workflow is configured to run after Duster finishes
  workflow_run:
    workflows: ["Duster Fix"]
    types:
      - completed
  pull_request:

jobs:
  test:
    name: PHPUnit Test

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: Cache Composer dependencies
      uses: actions/cache@v2
      with:
        path: ~/.composer/cache/files
        key: php-8.1-laravel-8.*-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: php-8.1-laravel-8.*-composer-

    - name: Cache npm dependencies
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: npm-

    - name: Create environment file
      run: |
        php -r "file_exists('.env') || copy('.env.example', '.env');"
        echo APP_ENV=testing >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        composer install --prefer-dist --no-interaction --no-progress --no-suggest
        npm install

    - name: Build Assets
      run: npm run build

    - name: Generate App Key
      run: php artisan key:generate

    - name: Run PHPUnit
      run: vendor/bin/phpunit
